backend/src/main.go

API to fetch cars  #23

---

backend/src/go.mod
backend/src/go.sum
backend/src/main.go

Enable CORS in backend   #27

---

backend/src/main.go

Creating an Account #2

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/Login.tsx
package-lock.json
package.json

React Routing Fixes #46

---

frontend/src/index.tsx

Fix React Router Fixes #49

---

backend/src/main.go

Fix backend Login  Fixes #53

---

frontend/src/Login.tsx

Remake Login Page Fixes #42

---

frontend/src/App.tsx
frontend/src/Register.tsx

Frontend for Register User Fixes #45

---

frontend/src/App.tsx
frontend/src/Viewallblog.tsx

Routing to blog Fixes #57

---

frontend/src/Createblogpost.tsx

Create Blog Post Fixes #58

---

backend/src/main.go

Fix register user Fixes #71

---

frontend/src/Createblogpost.tsx

Fix Create Blog Integration Issue Fixes #68

---

frontend/src/Viewpost.tsx

View Blog Post Fixes #61

---

frontend/src/Viewallblog.tsx

Add Link to View All Blog Page Fixes #79

---

frontend/src/App.tsx

Create Navbar Fixes #83

---

frontend/src/App.tsx

Fix Links in NavBar Fixes #85

---

backend/src/main.go

Add Image to a car Fixes #87

---

frontend/src/Comparecars.tsx
frontend/yarn.lock

Remake Car Compare Paze Fixes #96

---

frontend/src/Comparecars.tsx

Update Compare Cars Fixes #98

---

frontend/src/App.tsx

Update Routes Fixes #100

---

frontend/src/Viewpost.tsx

Add Delete Button To View Post Fixes #102

---

frontend/src/Viewallcars.tsx

Add Photo to View All Cars Fixes #104
